/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class MenuItem: Object, Decodable {
  private enum Keys: String, CodingKey {
    case icon = "icon"
    case title = "title"

    }

  @objc dynamic var icon: String?
  @objc dynamic var title: String?




  convenience required init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: Keys.self)
    let icon = try? container.decode(String?.self, forKey: .icon)
    let title = try? container.decode(String?.self, forKey: .title)
    self.init(icon: icon, title: title)
  }

  convenience init(icon: String?, title: String?) {
    self.init()
    self.icon = icon
    self.title = title

  }
}
