/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class SearchItems: Object, Decodable {
  private enum Keys: String, CodingKey {case items = "items"

    }

  let items = List<SearchItem>()





}
